config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks/", to: "tasks#index"
  get "task/:id", to: "tasks#show", as: 'task'
  get "tasks/new", to: "tasks#new"
  post "tasks/", to: "tasks#create"
  get "task/:id/edit", to: "tasks#edit", as: 'edit'
  patch "task/:id", to: "tasks#update"
  delete "task/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index         # GET /tasks
    @tasks = Task.all
  end

  def show          # GET /tasks/:id
    @task = Task.find(params[:id])
  end

  def new           # GET /tasks/new
    @task = Task.new
  end

  def create        # POST /tasks
    @task = Task.new(task_params)
    @task.save

    # no need for app/views/restaurants/create.html.erb
    redirect_to task_path(@task)
  end

  def edit          # GET /tasks/:id/edit
    @task = Task.find(params[:id])
  end

  def update        # PATCH /tasks/:id
    @task = Task.find(params[:id])
    @task.update(task_params)

    # no need for app/views/tasks/create.html.erb
    redirect_to task_path(@task)
  end

  def destroy       # DELETE /tasks/:id
    @task = Task.find(params[:id])
    @task.destroy

    # no need for app/views/tasks/create.html.erb
    redirect_to tasks_path
  end

  private

  def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:title, :details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <br>
  <%= f.text_field :title %>
  <br>
  <%= f.label :details %>
  <br>
  <%= f.text_field :details %>
  <br>
  <% if @task.completed == true %>
      <p><input type="checkbox" id="completed" value="true" checked> This task is not completed yet</p>
      <% else %>
      <p><input type="checkbox" id="completed" value="false"> Completed</p>
      <% end %>
  <%= f.submit %>

<% end %>

<%= link_to "Go back to task list", tasks_path %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul>
<% @tasks.each do |task| %>
    <div class="tasklook">
      <% if task.completed == true %>
      <i class="fa fa-check-square-o" aria-hidden="true"></i>
      <% else %>
      <i class="fa fa-square-o" aria-hidden="true"></i>
      <% end %>
        <%= link_to task.title, task_path(task) %>
        <%= link_to ('<i class="fa fa-trash-o" aria-hidden="true"></i>').html_safe, task_path(task),
        method: :delete,
        data: { confirm: "Are you sure?" } %>
    </div>
  <% end %>
</ul>

<%= link_to ('<button type="button" class="btn btn-primary">Add task</button>').html_safe, tasks_new_path %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <br>
  <%= f.text_field :title %>
  <br>
  <%= f.label :details %>
  <br>
  <%= f.text_field :details %>
  <br>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

<%= link_to "Go back to task list", tasks_path %>

app/views/tasks/show.html.erb
  <h2><%= @task.title %></h2>
  <div class="card"><%= @task.details %></div>
  <%= link_to "Edit this task", edit_path(@task) %>


<%= link_to "Go back to task list", tasks_path %>